--任务表
CREATE TABLE if not exists TASK(
   ID INT PRIMARY KEY  AUTO_INCREMENT ,
   NAME VARCHAR(50),
   CREATE_AT DATE,
   UPDATE_AT DATE
);

--用户表
create table if not exists ETUSER(
   ID INT PRIMARY KEY  AUTO_INCREMENT ,
   NAME VARCHAR(50),
   PWD VARCHAR(50),
   CREATE_AT DATE,
   UPDATE_AT DATE
)
